#!/bin/bash
#SBATCH --job-name=HW15-3-21_loop.sh
#SBATCH --partition=highmem_p
#SBATCH --ntasks=1
#SBATCH --mem=400gb
#SBATCH --time=50:00:00
#SBATCH --output=HW15-3-21_loop.%j.out
#SBATCH --error=HW15-3-21_loop.%j.err

cd /home/cfc85413/forloopsexamples030821

ml PLINK/2.00-alpha2.3-x86_64-20200914-dev


chr=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 21) #Either up the time max (though the parition would have to change) or chr can be split up


#Set genotype directory
genodir=("/scratch/cfc85413/chromfiles")
#Set out directiory
outdir=("/scratch/cfc85413/chromfiles_pgen")

for i in ${chr[@]}
do

plink2 \
 --bgen $genodir/ukb_imp_chr"$i"_v3.bgen ref-first \
 --sample $genodir/ukb_imp_v3.sample \
--make-pgen \
--out $outdir/chr"$i"

done

